# Generated by Django 4.1.7 on 2023-12-19 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleBOMCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('data_execucao', models.DateTimeField(auto_now=True, null=True)),
                ('data_corte', models.DateTimeField(blank=True, null=True)),
                ('projeto_bom', models.CharField(blank=True, max_length=200, null=True)),
                ('cwa', models.CharField(blank=True, max_length=200, null=True)),
                ('disciplina', models.CharField(blank=True, max_length=200, null=True)),
                ('cwp', models.CharField(blank=True, max_length=200, null=True)),
                ('iwp', models.CharField(blank=True, max_length=200, null=True)),
                ('position_status', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_status', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_padrao_fornecedor', models.CharField(blank=True, max_length=200, null=True)),
                ('descritivo_curto', models.CharField(blank=True, max_length=200, null=True)),
                ('descritivo_longo', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_material', models.CharField(blank=True, max_length=500, null=True)),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('unidade', models.CharField(blank=True, max_length=500, null=True)),
                ('ros_date', models.DateField(blank=True, null=True)),
                ('peso_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('desenho_vale_montagem', models.CharField(blank=True, max_length=500, null=True)),
                ('proc_pack', models.CharField(blank=True, max_length=500, null=True)),
                ('pacote_fornecimento', models.CharField(blank=True, max_length=500, null=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
            options={
                'verbose_name': 'BD Execucao BOM',
                'verbose_name_plural': 'BD Execucao BOM',
                'db_table': 'controlecompras_bom',
            },
        ),
    ]
