# Generated by Django 4.1.7 on 2023-04-06 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('role', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Usuário')], default=2)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BD Profile',
                'verbose_name_plural': 'BD Profile',
                'db_table': 'profile',
            },
        ),
    ]
