# Generated by Django 4.1.1 on 2022-11-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_profile_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
