# Generated by Django 4.1.7 on 2023-03-09 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_profile_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='whatsapp',
        ),
    ]
