# Generated by Django 4.1.7 on 2023-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_profile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Usuário')], default=2),
        ),
    ]
