# Generated by Django 4.1.7 on 2023-04-06 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DB Unidade',
                'verbose_name_plural': 'DB Unidade',
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('ativo', models.BooleanField(default=True)),
                ('total_projetos', models.IntegerField(blank=True, null=True)),
                ('total_user', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
            ],
            options={
                'verbose_name': 'DB Unidade',
                'verbose_name_plural': 'DB Unidade',
                'db_table': 'unidade',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DB Unidade Usuario',
                'verbose_name_plural': 'DB Unidade Usuario',
                'db_table': 'unidade_usuario',
            },
        ),
    ]
