# Generated by Django 4.1.7 on 2023-03-10 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DB Unidade Usuario',
                'verbose_name_plural': 'DB Unidade Usuario',
                'db_table': 'db_unidade_usuario',
            },
        ),
    ]
