# Generated by Django 4.1.7 on 2023-03-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
