# Generated by Django 4.1.7 on 2023-04-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagecronogramamaster',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
    ]
