# Generated by Django 4.1.7 on 2023-04-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        ('cronograma_master', '0002_alter_stagecronogramamaster_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='XerActvcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actv_code_id', models.IntegerField(blank=True, max_length=38, null=True)),
                ('parent_actv_code_id', models.CharField(blank=True, max_length=300, null=True)),
                ('actv_code_type_id', models.IntegerField(blank=True, max_length=38, null=True)),
                ('actv_code_name', models.CharField(blank=True, max_length=300, null=True)),
                ('short_name', models.CharField(blank=True, max_length=300, null=True)),
                ('seq_num', models.IntegerField(blank=True, max_length=38, null=True)),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cronograma_master.execucaocronomaster')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
            options={
                'verbose_name': 'BD XER Actvcode',
                'verbose_name_plural': 'BD XER Actvcode',
                'db_table': 'xer_actvcode',
            },
        ),
    ]
