# Generated by Django 4.1.7 on 2023-04-11 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0004_alter_xeractvcode_actv_code_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADFCronoMasterCronogramas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(blank=True, max_length=300, null=True)),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cronograma_master.execucaocronomaster')),
            ],
            options={
                'verbose_name': 'BD Execucao Cronograma Master Cronogramas ADF',
                'verbose_name_plural': 'BD Execucao Cronograma Master Cronogramas ADF',
                'db_table': 'execucao_cronograma_master_cronogramas_adf',
            },
        ),
    ]
