# Generated by Django 4.1.7 on 2023-04-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0005_adfcronomastercronogramas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xeractvcode',
            table='XER.ACTVCODE',
        ),
        migrations.AlterModelTable(
            name='xeractvtype',
            table='XER.ACTVTYPE',
        ),
        migrations.AlterModelTable(
            name='xercalendar',
            table='XER.CALENDAR',
        ),
        migrations.AlterModelTable(
            name='xerproject',
            table='XER.PROJECT',
        ),
        migrations.AlterModelTable(
            name='xerprojwbs',
            table='XER.PROJWBS',
        ),
        migrations.AlterModelTable(
            name='xerrsrc',
            table='XER.RSRC',
        ),
        migrations.AlterModelTable(
            name='xertask',
            table='XER.TASK',
        ),
        migrations.AlterModelTable(
            name='xertaskactv',
            table='XER.TASKACTV',
        ),
        migrations.AlterModelTable(
            name='xertaskpred',
            table='XER.TASKPRED',
        ),
        migrations.AlterModelTable(
            name='xerudftype',
            table='XER.UDFTYPE',
        ),
        migrations.AlterModelTable(
            name='xerudfvalue',
            table='XER.UDFVALUE',
        ),
    ]
