# Generated by Django 4.1.7 on 2023-04-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        ('cronograma_master', '0006_alter_xeractvcode_table_alter_xeractvtype_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XerTesteSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
            options={
                'db_table': 'XER.UDFTESTE',
            },
        ),
    ]


