# Generated by Django 4.1.7 on 2023-04-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0007_xertesteschema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XerTesteSchema',
        ),
    ]
