# Generated by Django 4.1.7 on 2023-04-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0008_delete_xertesteschema'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stagecronogramamaster',
            table='cronograma_master_stage_curva',
        ),
    ]
