# Generated by Django 4.1.7 on 2023-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0010_rename_seq_num_xertaskactv_proj_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaocronomaster',
            name='status_execucao_adf',
            field=models.CharField(blank=True, default='Concluído', max_length=200, null=True),
        ),
    ]
