# Generated by Django 4.1.7 on 2023-05-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0011_execucaocronomaster_status_execucao_adf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execucaocronomaster',
            name='status_execucao_adf',
        ),
        migrations.AddField(
            model_name='adfcronomastercronogramas',
            name='status_execucao_adf',
            field=models.CharField(blank=True, default='Concluído', max_length=200, null=True),
        ),
    ]
