# Generated by Django 4.1.7 on 2023-05-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        ('cronograma_master', '0012_remove_execucaocronomaster_status_execucao_adf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adfcronomastercronogramas',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto.projeto'),
        ),
    ]
