# Generated by Django 4.1.7 on 2023-05-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        ('cronograma_master', '0013_adfcronomastercronogramas_projeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageCronogramaMasterBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao_atividade', models.CharField(blank=True, max_length=200, null=True)),
                ('inicio', models.CharField(blank=True, max_length=200, null=True)),
                ('termino', models.CharField(blank=True, max_length=200, null=True)),
                ('duracao', models.CharField(blank=True, max_length=200, null=True)),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cronograma_master.execucaocronomaster')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
            options={
                'verbose_name': 'BD Stage Cronograma Master Baseline',
                'verbose_name_plural': 'BD Stage Cronograma Master Baseline',
                'db_table': 'cronograma_master_stage_baseline',
            },
        ),
    ]
