# Generated by Django 4.1.7 on 2023-05-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('core', '0001_initial'),
        ('projeto', '0001_initial'),
        ('cronograma_master', '0014_stagecronogramamasterbaseline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerCronoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ciacao', models.DateTimeField(auto_now=True, null=True)),
                ('data_execucao', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.profile')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
            options={
                'verbose_name': 'BD Container Cronograma Master',
                'verbose_name_plural': 'BD Container Cronograma Master',
                'db_table': 'container_cronograma_master',
            },
        ),
        migrations.AddField(
            model_name='execucaocronomaster',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cronograma_master.containercronomaster'),
        ),
    ]
