# Generated by Django 4.1.7 on 2023-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0015_containercronomaster_execucaocronomaster_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='containercronomaster',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
