# Generated by Django 4.1.7 on 2023-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0016_containercronomaster_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containercronomaster',
            name='data_execucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
