# Generated by Django 4.1.7 on 2023-05-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0017_alter_containercronomaster_data_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaocronomaster',
            name='inicio_carga',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucaocronomaster',
            name='inicio_preprocessament',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucaocronomaster',
            name='termino_carga',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucaocronomaster',
            name='termino_preprocessament',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execucaocronomaster',
            name='inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execucaocronomaster',
            name='termino',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
