# Generated by Django 4.1.7 on 2023-05-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0018_execucaocronomaster_inicio_carga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execucaocronomaster',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='execucaocronomaster',
            name='termino',
        ),
    ]
