# Generated by Django 4.1.7 on 2023-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0019_remove_execucaocronomaster_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaocronomaster',
            name='inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucaocronomaster',
            name='termino',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
