# Generated by Django 4.1.7 on 2023-11-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        ('cronograma_master', '0023_alter_adfcronomaster_execucao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaTaskrsrcAvancoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsrc_id', models.CharField(blank=True, max_length=200, null=True)),
                ('activity_id', models.CharField(blank=True, max_length=200, null=True)),
                ('task_status_code', models.CharField(blank=True, max_length=200, null=True)),
                ('role_id', models.CharField(blank=True, max_length=200, null=True)),
                ('acct_id', models.CharField(blank=True, max_length=200, null=True)),
                ('target_qty', models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto.projeto')),
            ],
            options={
                'verbose_name': 'BD Master Tabela Avanco Taskrsrc',
                'verbose_name_plural': 'BD Master Tabela Avanco Taskrsrc',
                'db_table': 'cronograma_tabela_avanco_taskrsrc',
            },
        ),
        migrations.CreateModel(
            name='TabelaTaskAvancoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(blank=True, max_length=200, null=True)),
                ('activity_status', models.CharField(blank=True, max_length=200, null=True)),
                ('wbs_code', models.CharField(blank=True, max_length=200, null=True)),
                ('op_cwp', models.CharField(blank=True, max_length=200, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=200, null=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto.projeto')),
            ],
            options={
                'verbose_name': 'BD Master Tabela Avanco Task',
                'verbose_name_plural': 'BD Master Tabela Avanco Task',
                'db_table': 'cronograma_tabela_avanco_task',
            },
        ),
    ]
