# Generated by Django 4.1.7 on 2024-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0024_tabelataskrsrcavancomaster_tabelataskavancomaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelataskavancomaster',
            name='OP_PACOTE_DE_SUPRIMENTOS',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskavancomaster',
            name='act_end_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskavancomaster',
            name='act_start_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskavancomaster',
            name='complete_pct',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskavancomaster',
            name='end_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskavancomaster',
            name='start_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskavancomaster',
            name='target_drtn_hr_cnt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
