# Generated by Django 4.1.7 on 2024-01-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0025_tabelataskavancomaster_op_pacote_de_suprimentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelataskrsrcavancomaster',
            name='act_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskrsrcavancomaster',
            name='act_end_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskrsrcavancomaster',
            name='act_qty',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskrsrcavancomaster',
            name='act_start_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskrsrcavancomaster',
            name='remain_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskrsrcavancomaster',
            name='remain_qty',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskrsrcavancomaster',
            name='rsrc_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabelataskrsrcavancomaster',
            name='target_cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
    ]
