# Generated by Django 4.1.7 on 2024-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma_master', '0026_tabelataskrsrcavancomaster_act_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabelataskavancomaster',
            name='complete_pct',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
    ]
