# Generated by Django 4.1.7 on 2023-11-06 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('fornecedores', '0001_initial'),
        ('usuario', '0001_initial'),
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaContratada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ciacao', models.DateTimeField(auto_now=True, null=True)),
                ('contratada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedores')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.profile')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
            options={
                'verbose_name': 'BD Container Cronogramas',
                'verbose_name_plural': 'BD Contratada Container Cronogramas',
                'db_table': 'contratada_container_cronogramas',
            },
        ),
        migrations.CreateModel(
            name='ExecucaoCronoContratadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('data_execucao', models.DateTimeField(auto_now=True, null=True)),
                ('inicio_preprocessament', models.TimeField(blank=True, null=True)),
                ('termino_preprocessament', models.TimeField(blank=True, null=True)),
                ('inicio_carga', models.TimeField(blank=True, null=True)),
                ('termino_carga', models.TimeField(blank=True, null=True)),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('termino', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('contratada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cronogramacontratadas.cronogramacontratada')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.profile')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UnidadeContratada', to='core.unidade')),
            ],
            options={
                'verbose_name': 'BD Execucao Cronograma Contratada',
                'verbose_name_plural': 'BD Execucao Cronograma Contratada',
                'db_table': 'contratada_cronograma_contratada',
            },
        ),
        migrations.CreateModel(
            name='StageCronogramaContratada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_corte', models.DateField(blank=True, null=True)),
                ('activity_id', models.CharField(blank=True, max_length=200, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=200, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=200, null=True)),
                ('spreadsheet_field', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True)),
                ('unidade', models.CharField(blank=True, max_length=200, null=True)),
                ('contratada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronogramacontratadas.cronogramacontratada')),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronogramacontratadas.execucaocronocontratadas')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
            options={
                'verbose_name': 'BD Stage Cronograma Contratada Curva',
                'verbose_name_plural': 'BD Stage Cronograma Contratada Curva',
                'db_table': 'cronograma_curva_contratada',
            },
        ),
    ]
