# Generated by Django 4.1.7 on 2023-11-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramacontratadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaocronocontratadas',
            name='data_corte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
