# Generated by Django 4.1.7 on 2023-11-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('projeto', '0001_initial'),
        ('cronogramacontratadas', '0002_execucaocronocontratadas_data_corte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguraCronogramaContratada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(blank=True, default='Activity ID', max_length=200, null=True)),
                ('resource_name', models.CharField(blank=True, default='Resource Name', max_length=200, null=True)),
                ('resource_type', models.CharField(blank=True, default='Resource Type', max_length=200, null=True)),
                ('spreadsheet_field', models.CharField(blank=True, default='Spreadsheet Field', max_length=200, null=True)),
                ('planilha', models.CharField(blank=True, default='Curva', max_length=200, null=True)),
                ('linha', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('coluna', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
            options={
                'verbose_name': 'BD Configura Cronograma Contratada',
                'verbose_name_plural': 'BD Configura Cronograma Contratada',
                'db_table': 'contratada_configura_cronograma',
            },
        ),
    ]
