# Generated by Django 4.1.7 on 2023-11-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        ('cronogramacontratadas', '0003_configuracronogramacontratada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StageCronogramaContratada',
            new_name='StageCronogramaContratadaCurva',
        ),
        migrations.CreateModel(
            name='StageCronogramaContratadaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_corte', models.DateField(blank=True, null=True)),
                ('activity_id', models.CharField(blank=True, max_length=200, null=True)),
                ('folga_livre', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('folga_total', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('duracao', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('avanco', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('data_inicio_bl', models.DateField(blank=True, null=True)),
                ('data_fim_bl', models.DateField(blank=True, null=True)),
                ('data_inicio_reprogramado', models.DateField(blank=True, null=True)),
                ('data_fim_reprogramado', models.DateField(blank=True, null=True)),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('work_package', models.CharField(blank=True, max_length=200, null=True)),
                ('contratada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronogramacontratadas.cronogramacontratada')),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cronogramacontratadas.execucaocronocontratadas')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
            ],
            options={
                'verbose_name': 'BD Stage Cronograma Contratada Atividade',
                'verbose_name_plural': 'BD Stage Cronograma Contratada Atividade',
                'db_table': 'cronograma_atividade_contratada',
            },
        ),
    ]
