# Generated by Django 4.1.7 on 2023-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramacontratadas', '0004_rename_stagecronogramacontratada_stagecronogramacontratadacurva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execucaocronocontratadas',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_fim_bl',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_fim_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_fim_reprogramado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_inicio_bl',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_inicio_reprogramado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
