# Generated by Django 4.1.7 on 2023-11-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramacontratadas', '0005_remove_execucaocronocontratadas_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='avanco',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='duracao',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='folga_livre',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='folga_total',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
    ]
