# Generated by Django 4.1.7 on 2023-11-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramacontratadas', '0006_alter_stagecronogramacontratadaatividade_avanco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagecronogramacontratadaatividade',
            name='OP_WP',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
