# Generated by Django 4.1.7 on 2023-11-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        ('cronogramacontratadas', '0008_alter_stagecronogramacontratadacurva_contratada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='contratada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cronogramacontratadas.cronogramacontratada'),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cronogramacontratadas.execucaocronocontratadas'),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto.projeto'),
        ),
    ]
