# Generated by Django 4.1.7 on 2023-11-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramacontratadas', '0009_alter_stagecronogramacontratadaatividade_contratada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagecronogramacontratadaatividade',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='stagecronogramacontratadaatividade',
            name='previsto',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=38, null=True),
        ),
    ]
