# Generated by Django 4.1.7 on 2023-11-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramacontratadas', '0010_stagecronogramacontratadaatividade_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_fim_bl',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_fim_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_fim_reprogramado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_inicio_bl',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_inicio_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagecronogramacontratadaatividade',
            name='data_inicio_reprogramado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
