# Generated by Django 4.1.7 on 2024-01-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramacontratadas', '0011_alter_stagecronogramacontratadaatividade_data_fim_bl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramacontratada',
            name='pacote',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
