# Generated by Django 4.1.7 on 2024-01-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramacontratadas', '0012_cronogramacontratada_pacote'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagecronogramacontratadaatividade',
            name='descricao',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
