# Generated by Django 4.1.7 on 2023-04-06 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(blank=True, max_length=300, null=True)),
                ('codigo_projeto', models.CharField(blank=True, max_length=300, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('inicio_projeto', models.DateField(blank=True, null=True)),
                ('termino_projeto', models.DateField(blank=True, null=True)),
                ('awp_master_index', models.BooleanField(default=False)),
                ('cronograma_master', models.BooleanField(default=False)),
                ('cronograma_contratadas', models.BooleanField(default=False)),
                ('bim', models.BooleanField(default=False)),
                ('ged', models.BooleanField(default=False)),
                ('suprimentos', models.BooleanField(default=False)),
                ('gestao_materiais', models.BooleanField(default=False)),
                ('comissionamento', models.BooleanField(default=False)),
                ('fase', models.IntegerField(choices=[(1, 'FEL 1'), (2, 'FEL 2'), (3, 'FEL 3'), (4, 'EXECUÇÃO')], default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unidade')),
            ],
            options={
                'verbose_name': 'BD Projetos',
                'verbose_name_plural': 'BD Projetos',
                'db_table': 'projetos',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DB Projeto Usuario',
                'verbose_name_plural': 'DB Projeto Usuario',
                'db_table': 'projeto_usuario',
            },
        ),
    ]
