# Generated by Django 4.1.7 on 2023-03-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_unidade'),
        ('projeto', '0003_usuario_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_projeto',
            name='unidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.unidade'),
            preserve_default=False,
        ),
    ]
