# Generated by Django 4.1.7 on 2023-03-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_usuario_projeto_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='fase',
            field=models.IntegerField(choices=[(1, 'FEL 1'), (2, 'FEL 2'), (3, 'FEL 3'), (4, 'EXECUÇÃO')], default=1),
        ),
    ]
