# Generated by Django 4.1.7 on 2023-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
