# Generated by Django 4.1.7 on 2023-03-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaold',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
