# Generated by Django 4.1.7 on 2023-03-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_profile_role'),
        ('ged', '0002_execucaold_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaold',
            name='data_execucao',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='execucaold',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.profile'),
        ),
    ]
