# Generated by Django 4.1.7 on 2023-03-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0003_execucaold_data_execucao_execucaold_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurald',
            name='certifica_na_1a_emissao',
        ),
        migrations.RemoveField(
            model_name='configurald',
            name='data_emissão_inicial_reprogramada',
        ),
        migrations.RemoveField(
            model_name='configurald',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='configurald',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='configurald',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='configurald',
            name='tipo_emissao_inicial',
        ),
        migrations.RemoveField(
            model_name='configurald',
            name='work_package',
        ),
        migrations.RemoveField(
            model_name='configurald',
            name='work_package_area',
        ),
    ]
