# Generated by Django 4.1.7 on 2023-03-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_unidade'),
        ('ged', '0005_alter_configurald_a1_equivalente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoEmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_tipo_emissao', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_emissão', models.CharField(blank=True, max_length=200, null=True)),
                ('certifica_primeira_emissão', models.BooleanField(blank=True, null=True)),
                ('cancelado', models.BooleanField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
            ],
            options={
                'verbose_name': 'BD Fluxo Emissao',
                'verbose_name_plural': 'BD Fluxo Emissao',
                'db_table': 'dbo_fluxo_emissao',
            },
        ),
    ]
