# Generated by Django 4.1.7 on 2023-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0006_fluxoemissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxoemissao',
            name='cancelado',
            field=models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO')], default=2),
        ),
        migrations.AlterField(
            model_name='fluxoemissao',
            name='certifica_primeira_emissão',
            field=models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO')], default=2),
        ),
    ]
