# Generated by Django 4.1.7 on 2023-03-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('ged', '0007_alter_fluxoemissao_cancelado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurald',
            name='sk',
        ),
        migrations.RemoveField(
            model_name='stageld',
            name='sk',
        ),
        migrations.AddField(
            model_name='execucaold',
            name='fase',
            field=models.IntegerField(choices=[(1, 'FEL 1'), (2, 'FEL 2'), (3, 'FEL 3'), (4, 'EXECUÇÃO')], default=1),
        ),
        migrations.AddField(
            model_name='execucaold',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fornecedores.fornecedores'),
        ),
    ]
