# Generated by Django 4.1.7 on 2023-03-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0009_configurald_coluna_configurald_linha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurald',
            name='tipo_emissao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
