# Generated by Django 4.1.7 on 2023-03-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_usuario_projeto_unidade'),
        ('ged', '0010_configurald_tipo_emissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='lod_processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto.projeto')),
            ],
            options={
                'verbose_name': 'BD Log processamento LD',
                'verbose_name_plural': 'BD Log processamento LD',
                'db_table': 'db_log_processamento_ld',
            },
        ),
    ]
