# Generated by Django 4.1.7 on 2023-03-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0011_lod_processamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageld',
            name='certifica_na_1a_emissao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
