# Generated by Django 4.1.7 on 2023-03-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0012_alter_stageld_certifica_na_1a_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageld',
            name='certifica_na_1a_emissao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
