# Generated by Django 4.1.7 on 2023-03-28 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0013_alter_stageld_certifica_na_1a_emissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lod_processamento',
            name='execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ged.execucaold'),
        ),
    ]
