# Generated by Django 4.1.7 on 2023-03-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_usuario_projeto_unidade'),
        ('core', '0003_alter_owner_owner'),
        ('ged', '0014_lod_processamento_execucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageGED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_revisao', models.CharField(blank=True, max_length=200, null=True)),
                ('documento', models.CharField(blank=True, max_length=200, null=True)),
                ('revisao', models.CharField(blank=True, max_length=200, null=True)),
                ('certificado', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_emissao', models.CharField(blank=True, max_length=200, null=True)),
                ('cancelado', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('disciplina', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_contratada', models.CharField(blank=True, max_length=200, null=True)),
                ('status_ged', models.CharField(blank=True, max_length=200, null=True)),
                ('data_atualizacao', models.DateField(blank=True, null=True)),
                ('ged_recebimento', models.CharField(blank=True, max_length=200, null=True)),
                ('data_grd_recebimento', models.DateField(blank=True, null=True)),
                ('data_analise', models.DateField(blank=True, null=True)),
                ('resultado_analise', models.CharField(blank=True, max_length=200, null=True)),
                ('e_certificadora', models.CharField(blank=True, max_length=200, null=True)),
                ('grd_devolucao', models.CharField(blank=True, max_length=200, null=True)),
                ('formato', models.CharField(blank=True, max_length=200, null=True)),
                ('paginas', models.CharField(blank=True, max_length=200, null=True)),
                ('a1_equivalente', models.CharField(blank=True, max_length=200, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_atividade', models.CharField(blank=True, max_length=200, null=True)),
                ('work_package_area', models.CharField(blank=True, max_length=200, null=True)),
                ('work_package', models.CharField(blank=True, max_length=200, null=True)),
                ('rev_num', models.CharField(blank=True, max_length=200, null=True)),
                ('execucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ged.execucaold')),
            ],
            options={
                'verbose_name': 'BD Stage GED',
                'verbose_name_plural': 'BD Stage GED',
                'db_table': 'db_stage_ged',
            },
        ),
        migrations.CreateModel(
            name='ConfiguraGED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('revisao', models.CharField(blank=True, max_length=200, null=True)),
                ('codigos_classe_descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_disciplina', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo_1', models.CharField(blank=True, max_length=200, null=True)),
                ('titulo_2', models.CharField(blank=True, max_length=200, null=True)),
                ('nome_fornecedor', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_fornecedor', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('updated', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_grd_entrada', models.CharField(blank=True, max_length=200, null=True)),
                ('data_grd_entrada', models.CharField(blank=True, max_length=200, null=True)),
                ('data_analise', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo_emissao', models.CharField(blank=True, max_length=200, null=True)),
                ('formato_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_cwa', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_wp', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_tipo_emissao', models.CharField(blank=True, max_length=200, null=True)),
                ('atual_responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('planilha', models.CharField(blank=True, max_length=200, null=True)),
                ('linha', models.CharField(blank=True, max_length=200, null=True)),
                ('coluna', models.CharField(blank=True, max_length=200, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto.projeto')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.unidade')),
            ],
            options={
                'verbose_name': 'BD Configura GED',
                'verbose_name_plural': 'BD Configura GED',
                'db_table': 'db_configura_ged',
            },
        ),
    ]
