# Generated by Django 4.1.7 on 2023-03-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_usuario_projeto_unidade'),
        ('ged', '0015_stageged_configuraged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuraged',
            old_name='codigo_cwa',
            new_name='data_atualizacao',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='codigo_tipo_emissao',
            new_name='data_grd_recebimento',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='codigo_wp',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='codigos_classe_descricao',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='data_grd_entrada',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='formato_documento',
            new_name='formato',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='motivo_emissao',
            new_name='grd_recebimento',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='nome_disciplina',
            new_name='numero_contratada',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='nome_fornecedor',
            new_name='resultado_analise',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='numero_documento',
            new_name='status_ged',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='numero_fornecedor',
            new_name='tipo_documento',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='numero_grd_entrada',
            new_name='tipo_emissao',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='state',
            new_name='work_package',
        ),
        migrations.RenameField(
            model_name='configuraged',
            old_name='updated',
            new_name='work_package_area',
        ),
        migrations.AddField(
            model_name='stageged',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto.projeto'),
        ),
        migrations.AddField(
            model_name='stageld',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projeto.projeto'),
        ),
    ]
