# Generated by Django 4.1.7 on 2023-03-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ged', '0016_rename_codigo_cwa_configuraged_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execucaold',
            name='fase',
        ),
    ]
