# Generated by Django 4.1.7 on 2023-03-31 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_owner_owner'),
        ('ged', '0017_remove_execucaold_fase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoDevolucaoGED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla_devolucao', models.CharField(blank=True, max_length=200, null=True)),
                ('certificado', models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO')], default=2)),
                ('cancelado', models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO')], default=2)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.owner')),
            ],
            options={
                'verbose_name': 'BD Fluxo Devolucao GED',
                'verbose_name_plural': 'BD Fluxo Devolucao GED',
                'db_table': 'dbo_fluxo_devolucao_ged',
            },
        ),
    ]
