# Generated by Django 4.1.7 on 2023-03-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_profile_role'),
        ('core', '0003_alter_owner_owner'),
        ('fornecedores', '0002_fornecedores_cidade'),
        ('projeto', '0005_projeto_fase'),
        ('ged', '0018_fluxodevolucaoged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraged',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.owner'),
        ),
        migrations.AlterField(
            model_name='configuraged',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='configuraged',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='configurald',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='configurald',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='execucaold',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedores'),
        ),
        migrations.AlterField(
            model_name='execucaold',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.profile'),
        ),
        migrations.AlterField(
            model_name='execucaold',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='execucaold',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='fluxodevolucaoged',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.owner'),
        ),
        migrations.AlterField(
            model_name='lod_processamento',
            name='execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ged.execucaold'),
        ),
        migrations.AlterField(
            model_name='lod_processamento',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='stageged',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='stageld',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projeto.projeto'),
        ),
    ]
