# Generated by Django 4.1.7 on 2023-03-31 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_projeto_fase'),
        ('ged', '0019_alter_configuraged_owner_alter_configuraged_projeto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageged',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
        migrations.AlterField(
            model_name='stageld',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projeto.projeto'),
        ),
    ]
